#!/bin/sh

yarn webpack --mode development

zip -r9 dist/bundle.zip bundle.js node_modules/kuromoji/dict

aws s3 cp dist/ s3://$BUCKET_NAME/lambda/ --recursive --exclude=.keep --exclude=.DS_Store

aws cloudformation package --template-file master.yaml --output-template-file dist/output.yaml --s3-bucket $CFN_STACK_NAME

aws cloudformation deploy --template-file dist/output.yaml --stack-name $CFN_STACK_NAME --capabilities CAPABILITY_IAM --parameter-overrides S3BucketName=$CFN_STACK_NAME
